development:
  secret_key_base: 'development-secret-key-base'
  jwt_secret_key: 'development-jwt-secret-key'

test:
  secret_key_base: 'test-secret-key-base'
  jwt_secret_key: 'test-jwt-secret-key'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_secret_key: <%= ENV['JWT_SECRET_KEY'] %>